### ISSUE TITLE
Mirror Blacks out when using module

### ISSUE THREAD

**Issue by JCleary682** [ralberth/MMM-MysqlQuery#11]
Hi

I am currently trying to use the module to run a general query in a database hosted by my universities lamp server. The screen appears to just black out when it is run, however im unsure what is happening here. I have attached a screenshot of the error logs from pm2 and I will add in my config too, although I have removed any info which could cause security issues. 

<img width="925" alt="Screenshot 2020-01-31 at 22 35 58" src="https://user-images.githubusercontent.com/32579521/73579495-82d64200-447a-11ea-8974-d11d220113bd.png">

{
		    module: 'MMM-MysqlQuery',
		    position: "top_right",
		    config: {
			connection: {
			    host: "***********",
			    port: 3306,
			    user: "**********",
			    password: "********",
			    database: "******"
			},
			query: `select name
				from miiLearning_Users
				order by name`,
				intervalSeconds: 15 * 60,
			emptyMessage: "No Users",
			columns: [
			    { name: "name",     title: "Name", cssClass: "left", nullValue: "???" },
			]
		    }
		},

**Comment by JCleary682** [comment]
upon review this appears to have been my mistake, I simply forgot to run npm install when I installed the module (My bad)
Closing issue

**Comment by ralberth** [comment]
Hi!  Just saying 'hi', since I didn't get a chance to chat with you about this.  Everything else going OK?
