### ISSUE TITLE
How to display table title ?

### ISSUE THREAD

**Issue by 0xEzis** [ralberth/MMM-MysqlQuery#13]
Hello !
I would like to display a title with my table, the same way you did with "MYSQL SPICIES" on your example. Yet i don't understand how did you do so, there's no title option to add in config{}.

The situation if needed : 
I use MMM-Carousel in order to display to different table at the same time with a slide between them every 10s. In order to understand faster which table is currently displaying i want to have a title linked to the subject of the table.

**Comment by ralberth** [comment]
I'd recommend the `headers` option from MM directly.  Check out https://docs.magicmirror.builders/modules/configuration.html for some details.

**Comment by 0xEzis** [comment]
worked perfectly thanks ! and for all the modules thats great to easily customize
